### ISSUE TITLE
CCCP not finding optimal solution.

### ISSUE THREAD

**Issue by bnaras** [bpfaff/cccp#2]
The setting of tolerances to 1-6 seems to work for smaller problems, but fails when I increase the problem size. Here I attach matrices containing 52 rows (`gh.RDS` in the zip file). The associated code is below (and actually of the same form as I had emailed):

```{r}
library(cccp)
gh  <- readRDS("gh.RDS")

clist  <- list(
    cccp::socc(F = -gh$G[2:52, , drop = FALSE],
               g = gh$h[2:52, , drop = FALSE],
               d = -gh$G[1, , drop = FALSE],
               f = gh$h[1, , drop = FALSE])
)

results <- cccp::cccp(q = c(1, 0, 0),
                      cList = clist,
                      optctrl = cccp::ctrl(abstol = 1e-6, feastol = 1e-6, reltol = 1e-6)
                      )
sessionInfo()
```
Results and data here in [result.zip](https://github.com/bpfaff/cccp/files/4519779/result.zip).

CCCP seems to get close to the solution around iteration 13 or15 quickly, but then it wanders off away from the optimum. Sometimes the resulting error is that the problem is infeasible. 

Incidentally, all other solvers I use (ECOS, MOSEK, OSQP) all solve this without a problem.

**Comment by bpfaff** [comment]
Dear Naras,

as by my email just sent; the issue has been fixed (see last commit).

Many thanks for all your endevours and your meticulous reports in earlier conversations.

Best wishes,
Bernhard

**Comment by bnaras** [comment]
Dear Bernhard,
Thank you. Your work on `cccp` is much appreciated.  I am writing again because I don't think the fix solves the problem.  While the program terminates, the primal and dual objectives are too far off, resulting in the wrong objective value; see output in attached.

[results2.zip](https://github.com/bpfaff/cccp/files/4525625/results2.zip)

For comparison, I did another experiment, which is to solve the same problem in python using `cvxopt` which I also include above. This may aid in figuring out where the difference occurs. For this problem, the result should be 281933.737925681.

I don't know the internal details,  but the original version got close to this result I think. Let me know if I can help further.

Best wishes,
-Naras
