### ISSUE TITLE
Suppress warnings in l1()?

### ISSUE THREAD

**Issue by guido-s** [bpfaff/cccp#5]
Hi,

We just added a new method to the development version of R package **netmeta** which uses _l1()_ inside _netcontrib()_ to calculate network contributions (https://github.com/guido-s/netmeta/commit/2bf00660e5733030bf90ded8941235929626b4f4).

Due to the network structure we have many zeros resulting in loads of warnings like
warning: solve(): system is singular; attempting approx solution
and
warning: solve(): system is singular (rcond: 1.38373e-39); attempting approx solution

Would it be possible to add an argument to _l1()_ to suppress these warnings?
Or is there another possibility to get rid of the warnings?

Best,
Guido

P.S. See, e.g., the output of the following commands:
library("netmeta")
example(netcontrib)
netcontrib(net1, method = "cccp")

**Comment by bpfaff** [comment]
Hi Guido,

yes, you can use ctrl(trace=FALSE) as argument optctrl in the call of l1.

Best wishes,
Bernhard

*Von: *Guido Schwarzer ***@***.***>
*An: *bpfaff/cccp ***@***.***>
*Kopie: *Subscribed ***@***.***>
*Datum: *31.07.2023 14:06:42
*Betreff: *[bpfaff/cccp] Suppress warnings in l1()? (Issue #5)

**Comment by guido-s** [comment]
I should have said that we are already using this argument in our _l1()_ call. Here is the printout for a reduced example (which produces fewer warnings):

```
> res <- l1(A1, optctrl = ctrl(trace=FALSE))

warning: solve(): system is singular (rcond: 1.90474e-18); attempting approx solution

warning: solve(): system is singular (rcond: 1.90474e-18); attempting approx solution
>
> res <- l1(A1, optctrl = ctrl(trace=TRUE))

warning: solve(): system is singular (rcond: 1.90474e-18); attempting approx solution

warning: solve(): system is singular (rcond: 1.90474e-18); attempting approx solution
Optimal solution found.
```

Does this mean that the argument ctrl(trace=FALSE) doesn't work as expected?

**Comment by bpfaff** [comment]
Ups, sorry, no it does work as intended, though I erroneously assumed that warnings() are supressed, too. Having said this, does a prior supressWarnings() is a remedy.

Best wishes,
Bernhard

*Von: *Guido Schwarzer ***@***.***>
*An: *bpfaff/cccp ***@***.***>
*Kopie: *Bernhard Pfaff ***@***.***>; Comment ***@***.***>
*Datum: *31.07.2023 18:06:10
*Betreff: *Re: [bpfaff/cccp] Suppress warnings in l1()? (Issue #5)

**Comment by guido-s** [comment]
Neither `suppressWarnings()` nor `options(warn = -1)` suppresses the warnings.

Best wishes,
Guido

**Comment by guido-s** [comment]
I fixed the problem in https://github.com/guido-s/netmeta/commit/b37649927611778de36ddc0ad9f52ab34e76315f using

`
invisible(capture.output(..., type = "message"))
`

Thanks to @wviechtb to point me at https://stackoverflow.com/questions/49694552/suppress-messages-from-underlying-c-function-in-r .
